### ISSUE TITLE
0.3.0 in splunkbase?

### ISSUE THREAD

**Issue by daaain** [Bre77/TA-googlebigquery#27]
Just realised that splunkbase still has 0.2.3, do you know when they are going to release 0.3.0?

**Comment by Bre77** [comment]
It is on Splunkbase if you look under version history, however I just set it as the default too to avoid confusion.

**Comment by daaain** [comment]
Oh I see! Do you know why isn't it compatible with Splunk Cloud?

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/69962/197485978-d966fdf3-a53d-426d-b063-7ed5ca63258c.png">

**Comment by Bre77** [comment]
This app has binary files so it requires a manual review by Splunk for every new version. I just checked and the review hasn't been assigned to anyone yet. You could upload it as a private app, or unfortunately will have to wait.

The older version works just fine, it's only missing the small checkpoint changes.

**Comment by daaain** [comment]
I tried to download it and package it with [slim](https://dev.splunk.com/enterprise/docs/releaseapps/packageapps/packagingtoolkit/#Install-the-Splunk-Packaging-Toolkit) as a private app and after a few back and forths with having to delete `.gitignore` and `.splunkbaseid` and setting file permissions I was able to get it to pass the verification, but the install eventually fails anyway without any meaningful error message:

<img width="773" alt="Screenshot 2022-10-25 at 10 59 17" src="https://user-images.githubusercontent.com/69962/197735634-e123b2ec-c2b6-491f-bea7-650d1beff352.png">

It's currently only possible to install the app from Splunkbase by opening a support case and I couldn't see an option to install the older version somehow:

<img width="624" alt="image" src="https://user-images.githubusercontent.com/69962/197731449-bcff7c84-75d7-46d9-996c-4f994767e0c5.png">

Sorry for bothering you with these generic Splunk issues by the way, but I'll at least make sure to document my findings to make it possible for others to self-support 😅

**Comment by Bre77** [comment]
Would it help if I set the default version back to the cloud vetted one? I might do that until 2.0 gets vetted.

**Comment by daaain** [comment]
No, it was like that even before I opened the issue here but I thought if I have to go through the support case route at least it should be the latest version. But thanks anyway!

**Comment by daaain** [comment]
Thanks a lot for the pointer, after a fair bit of back and forth and chasing down with support I figured that the IDM is a separate, companion instance to the main Splunk Cloud one, got the app installed by support and the data is happily flowing now 🙌
